### ISSUE TITLE
Using latest, all builds fail. Cannot make dir.

### ISSUE THREAD

**Issue by znorris** [GoogleCloudPlatform/jenkins-packer-agent#3]
Using `jenkins-packer-agent:latest` causes all builds to fail when attempting to make the jenkins project directory:

```
Started by user anonymous
Building remotely on jenkins-agent-68lt1 (swarm gcp-packer) in workspace /home/jenkins-agent/workspace/test
java.io.IOException: Failed to mkdirs: /home/jenkins-agent/workspace/test
    at hudson.FilePath.mkdirs(FilePath.java:1154)
    at hudson.model.AbstractProject.checkout(AbstractProject.java:1263)
    at hudson.model.AbstractBuild$AbstractBuildExecution.defaultCheckout(AbstractBuild.java:622)
    at jenkins.scm.SCMCheckoutStrategy.checkout(SCMCheckoutStrategy.java:86)
    at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:528)
    at hudson.model.Run.execute(Run.java:1759)
    at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
    at hudson.model.ResourceController.execute(ResourceController.java:89)
    at hudson.model.Executor.run(Executor.java:240)
Finished: FAILURE
```

This image does not result in error:
`jenkins-packer-agent:master-1f6b3f6`

**Comment by evandbrown** [comment]
Thanks for catching this, Zach. Did you notice it will deploying the [kube-jenkins-imager](https://github.com/GoogleCloudPlatform/kube-jenkins-imager) project? I've removed the `:latest` tag from the image repository, but would appreciate knowing if there are other references to it out there.

**Comment by znorris** [comment]
Yes, that's when I noticed it. There is also a reference to it here: https://cloud.google.com/solutions/automated-build-images-with-jenkins-kubernetes

There seem to be some differences between the github page and the Google Solutions page. For instance `:latest` was needed for `jekins-leader` which is referenced at Google Solutions, but not in the git repo. If there is any way I can help let me know. It has been a big help.

**Comment by evandbrown** [comment]
Images in the kube-jenkins-imager were updated to resolve this: https://github.com/GoogleCloudPlatform/kube-jenkins-imager/blob/master/images.cfg

Thanks again for bringing this to my attention, and happy new year!
